services:
  web:
    build:
      context: ..
      dockerfile: app/Dockerfile
    container_name: tokokita_web_staging
    env_file:
    - ../.env.example
    depends_on:
      - db
    networks:
      - tokonet_staging

  db:
    image: postgres:15
    container_name: tokokita_db_staging
    restart: unless-stopped
    environment:
      POSTGRES_DB: tokokita
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - dbdata_staging:/var/lib/postgresql/data
    networks:
      - tokonet_staging

  nginx:
    image: nginx:latest
    container_name: tokokita_nginx_staging
    ports:
      - "127.0.0.1:3000:80"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    networks:
      - tokonet_staging

networks:
  tokonet_staging:

volumes:
  dbdata_staging: