name: Test Self-Hosted Runner

on:
  workflow_dispatch:

jobs:
  test-runner:
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Runner Info
        run: |
          echo "Runner berhasil!"
          echo "Hostname: $(hostname)"
          echo "User: $(whoami)"
          echo "Kernel: $(uname -r)"
          echo "Docker:"
          docker version
