FROM python:3.10-slim

WORKDIR /app

LABEL org.opencontainers.image.source="https://github.com/malikstudent/tokokita_tes"

COPY app/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app/ .

ENV FLASK_APP=app.py

CMD ["gunicorn", "--bind", "0.0.0.0:5000", "app:app"]